spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimeZone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: bmr123
    driver-class-name: com.mysql.cj.jdbc.Driver